"""
Social network profile schema for Stage 4 of the population pipeline.

Each SocialProfile is generated by the LLM (EXP04) for one archetype and
captures the social connectivity parameters needed to construct that
archetype's network layer.

Architecture adapts the multi-layer co-location method of Jiang, Crooks,
Kavak et al. (2022) — four layers:
  - Household layer  : complete graph over realized household members, plus a
                       few home_contacts-driven extra-household kin ties
  - Workplace layer  : Newman-Watts-Strogatz with archetype-specific k and p
  - School layer     : Newman-Watts-Strogatz over school co-attendees + guardians
  - Community layer  : nationality × parish homophily/bridging layer (replaces
                       Jiang's daycare layer; a shared-attribute, not co-location,
                       layer suited to Andorra)

The NWS defaults k=4, p=0.3 follow Jiang, Yin, Wang & Crooks (2024, Scientific
Data), which state them verbatim; the 2022 paper establishes the method and the
≤5-member core-group (Dunbar) rule.

The three contact-rate parameters (home/work/community_contacts) are bounded by
Prem et al. 2021 Spain contact-matrix priors (contact_priors.py), analogous to
how place preferences are bounded by Eurostat structural priors. The homophily
and bridging parameters have no Prem anchor (the matrices carry no nationality
axis) and are LLM/expert priors validated post-hoc via realized assortativity.
"""

from dataclasses import dataclass, asdict


# ── JSON schema shown to the LLM ──────────────────────────────────────────────
SOCIAL_PROFILE_SCHEMA = """
{
  "home_contacts":           1.5-6.0,   // mean daily home contacts (Prem 2021 Spain prior ±40%)
  "work_contacts":           0.0-15.0,  // mean daily workplace contacts (0.0 for non-employed)
  "community_contacts":      0.5-8.0,   // mean daily community/other contacts

  "workplace_k":             2-8,       // NWS nearest-neighbour count (integer; Jiang 2024 default: 4)
  "workplace_p":             0.05-0.50, // NWS shortcut edge probability (Jiang 2024 default: 0.3)

  "nationality_homophily":   0.0-1.0,   // 0=fully mixed; 1=same nationality only
  "age_homophily":           0.0-1.0,   // 0=fully mixed; 1=same age band only
  "bridging_weight":         0.0-1.0    // cross-group tie probability — must align with bridging_capital
}
"""


@dataclass
class SocialProfile:
    # Contact rates (constrained by Prem 2021 Spain matrices)
    home_contacts:         float   # expected mean daily home contacts
    work_contacts:         float   # expected mean daily workplace contacts
    community_contacts:    float   # expected mean daily community contacts

    # Newman-Watts-Strogatz topology parameters (Jiang et al. 2022)
    workplace_k:           int     # nearest-neighbour ring count
    workplace_p:           float   # shortcut edge probability

    # Social mixing preferences
    nationality_homophily: float   # within-nationality tie preference
    age_homophily:         float   # within-age-band tie preference
    bridging_weight:       float   # cross-group tie probability

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class NetworkLayers:
    """Four-layer social network for the full population (V2.2)."""
    agent_ids:        list           # agent_id strings, index-ordered
    household_edges:  list           # (int_idx, int_idx) tuples
    workplace_edges:  list           # (int_idx, int_idx) tuples
    school_edges:     list           # (int_idx, int_idx) tuples
    community_edges:  list           # (int_idx, int_idx) tuples

    LAYER_NAMES = ("household", "workplace", "school", "community")

    def edge_count(self) -> dict:
        d = {name: len(getattr(self, f"{name}_edges")) for name in self.LAYER_NAMES}
        d["total"] = sum(d.values())
        return d

    def to_agent_pairs(self, layer: str) -> list:
        """Return (agent_id, agent_id) string pairs for a named layer."""
        edges = getattr(self, f"{layer}_edges")
        ids = self.agent_ids
        return [(ids[i], ids[j]) for i, j in edges]
