"""
Validate LLM-generated place_preferences in population.json.

Place preferences are now generated by the LLM as part of archetype creation
and perturbed per agent in expand.py.  This script runs the four mathematical
validity metrics against the existing population to check quality.

Run from research/profile_generation/:
    python add_place_prefs.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from place_preferences import PlacePreferenceValidator

POP_DIR = Path(__file__).parent / "results" / "andorra_population"

path = POP_DIR / "population.json"
if not path.exists():
    print(f"population.json not found at {path}")
    sys.exit(1)

print(f"Loading population.json...", end=" ", flush=True)
with open(path) as f:
    population = json.load(f)
print(f"{len(population):,} agents")

has_prefs = sum(1 for a in population if a.get("place_preferences"))
print(f"Agents with place_preferences: {has_prefs:,} / {len(population):,}")
if has_prefs == 0:
    print("No place_preferences found — re-run archetype generation with updated schema.")
    sys.exit(1)

sample    = population[:10_000]
validator = PlacePreferenceValidator(sample)
report    = validator.report()

print(f"\n{'─'*54}")
print(f"  Place Preference Validity Report  (n={report['n_profiles']:,})")
print(f"{'─'*54}")
print(f"  ARA  Activity Rate Alignment     {report['ara']:.4f}")
print(f"  MDP  Monotone Demographic Preds  {report['mdp']:.4f}")
print(f"  SCC  Social Cluster Coherence    {report['scc']:.4f}")
print(f"  SEF  Shannon Entropy Floor       {report['sef']:.4f}")
print(f"{'─'*54}")
print(f"  Composite                        {report['composite']:.4f}")
print(f"{'─'*54}")

print("\nARA detail (synthetic mean vs Eurostat structural prior):")
for did, d in sorted(report["detail_ara"].items()):
    flag = "!" if d["relative_error"] > 0.25 else " "
    print(f"  {flag} {did:<4}  syn={d['synthetic_mean']:.3f}  "
          f"ref={d['reference']:.3f}  err={d['relative_error']:.3f}")

print("\nMDP detail (Spearman signed correlations with demographics):")
fails  = [r for r in report["detail_mdp"] if not r["pass"]]
passes = [r for r in report["detail_mdp"] if r["pass"]]
print(f"  Passed: {len(passes)}/{len(report['detail_mdp'])}")
if fails:
    print("  Failed checks:")
    for r in fails:
        print(f"    {r['layer']} × {r['feature']:3s}  expected={r['expected']:8s}  ρ={r['rho']}")

print("\nSCC detail (social cluster pairwise Pearson r):")
for r in report["detail_scc"]:
    mark = "pass" if r["pass"] else "FAIL"
    print(f"  {r['pair']}  r={r['r']:.3f}  [{mark}]")

sef_d = report["detail_sef"]
print(f"\nSEF: mean H_norm={sef_d['mean_h_norm']:.3f}  "
      f"min={sef_d['min_h_norm']:.3f}  "
      f"fraction≥{sef_d['threshold']}={sef_d['fraction_above']:.3f}")

print("\nDone.")
