"""
Place preference validation — mathematical quality checks on LLM-generated D-layer weights.

Place preferences are generated by the LLM as part of archetype creation (schema.py
OUTPUT_SCHEMA), constrained by Eurostat structural priors and demographic logic baked
into the generation prompt.  This module provides four population-level validity metrics
to detect drift or implausible outputs after generation.

Generation approach
────────────────────
LLM-generated preferences are bounded, explainable, and checked against real-world
patterns.  The LLM reasons holistically from each agent's full profile — personality,
values, age, income, employment, household — and adjusts from the Eurostat structural
priors listed in the prompt.  This replaces the previous RUM β-coefficient approach,
which gave false precision (specific magnitudes were hand-specified, not estimated).

Mathematical validity metrics
──────────────────────────────
Four metrics assess internal validity of the generated preference vectors.
All return values in [0, 1], higher = better:

  ARA — Activity Rate Alignment
        Population-mean preferences vs Eurostat structural priors
        (HETUS, Eurobarometer, EU-SILC, EHIS, Pew, AES — see place_layers.py).
        A score < 0.80 indicates the LLM is systematically over- or under-rating
        a destination type at population level.

  MDP — Monotone Demographic Predictions
        Signed Spearman rank correlations with age and income, tested against
        expected directions from published demography literature.
        Checks that e.g. healthcare preference increases with age.

  SCC — Social Cluster Coherence
        Pearson intercorrelations within the social/leisure destination cluster
        (D21 Restaurant, D22 Café, D23 Bar, D24 Pub) should all be positive
        (common driver: extraversion + hedonism).

  SEF — Shannon Entropy Floor
        Each agent's preference vector should have meaningful entropy (not
        collapsed onto one destination type).  Fraction of agents with
        normalised entropy ≥ 0.65.

Usage
─────
  validator = PlacePreferenceValidator(profiles)
  report    = validator.report()
"""

from __future__ import annotations

import math
import numpy as np
from scipy import stats

from place_layers import (
    LAYER_REGISTRY, ALL_LAYER_IDS,
    SOCIAL_CLUSTER, EUROSTAT_BENCHMARKED_IDS,
)


# ── Income rank map ────────────────────────────────────────────────────────────
# Used to normalise income_bracket to [0, 1] for MDP metric.
_INCOME_RANK: dict[str, int] = {
    k: i for i, k in enumerate(
        ["precarious", "low", "lower_middle", "middle",
         "upper_middle", "comfortable", "wealthy"]
    )
}
_INCOME_MAX = 6


# ── Mathematical validity metrics ──────────────────────────────────────────────

# Expected monotonic relationships with age and income.
# Each entry: (layer_id, feature_name, expected_sign)
# feature "age" uses raw profile.age; "inc" uses normalized income rank.
# Grounded in: GS97, HETUS 2010, ATUS 2022.
MONOTONE_CHECKS: list[tuple[str, str, str]] = [
    # Age → positive
    ("D8",  "age", "positive"),   # Healthcare increases with age [GS97]
    ("D11", "age", "positive"),   # Senior housing increases with age [GS97]
    ("D17", "age", "positive"),   # Pharmacy increases with age [GS97, BV94]
    ("D7",  "age", "positive"),   # Religious attendance increases with age [HETUS]
    # Age → negative
    ("D5",  "age", "negative"),   # Education preference peaks in youth [GS97]
    ("D23", "age", "negative"),   # Bar attendance declines with age [GS97]
    ("D18", "age", "negative"),   # Career training peaks in youth/early career
    ("D27", "age", "negative"),   # Mountain/ski activity declines with age [GS97]
    # Income → positive
    ("D13", "inc", "positive"),   # Executive housing with higher income
    ("D21", "inc", "positive"),   # Restaurant spending increases with income [ATUS22]
    ("D3",  "inc", "positive"),   # Retail spending increases with income [ATUS22]
    ("D26", "inc", "positive"),   # Cultural venue spending increases with income [ATUS22]
    # Income → negative
    ("D12", "inc", "negative"),   # Affordable housing need decreases with income
    ("D11", "inc", "negative"),   # Senior housing financial need (low income)
]

# Reference rates for ARA metric — Eurostat structural priors for all modelled layers.
# These are the ground-truth targets for population-level mean preferences.
_ARA_TARGETS: dict[str, float] = {
    spec.layer_id: spec.base_rate()
    for spec in LAYER_REGISTRY
    if spec.layer_id in EUROSTAT_BENCHMARKED_IDS
}


class PlacePreferenceValidator:
    """
    Mathematical validity checker for a synthetic population's place preferences.

    Usage
    ─────
    validator = PlacePreferenceValidator(profiles)
    report    = validator.report()
    # report is a dict with four scores and detailed sub-results.
    """

    def __init__(self, profiles: list[dict]):
        self.profiles = profiles
        self._pref_matrix: dict[str, list[float]] = {}
        self._age_vector:  list[float] = []
        self._inc_vector:  list[float] = []
        self._built = False

    def _build(self):
        if self._built:
            return
        for did in ALL_LAYER_IDS:
            self._pref_matrix[did] = []
        for p in self.profiles:
            prefs = p.get("place_preferences") or {}
            if not prefs:
                continue
            for did in ALL_LAYER_IDS:
                v = prefs.get(did)
                if v is not None:
                    self._pref_matrix[did].append(float(v))
            self._age_vector.append(float(p.get("age", 35)))
            income = p.get("income_bracket", "middle")
            self._inc_vector.append(_INCOME_RANK.get(income, 3) / _INCOME_MAX)
        self._built = True

    # ── ARA: Activity Rate Alignment ─────────────────────────────────────────

    def activity_rate_alignment(self) -> tuple[float, dict]:
        """
        Compare population-mean preference weights against Eurostat structural priors.

        Score = 1 − mean(|synthetic_mean − reference| / reference)
        Clamped to [0, 1].  Score of 1.0 = perfect alignment.

        References: HETUS 2010, Eurobarometer 525 (2022), EU-SILC 2015, EHIS Wave 2,
        Pew Research 2018, AES 2022 — see place_layers.py structural_prior fields.
        """
        self._build()
        deviations = {}
        for did, ref in _ARA_TARGETS.items():
            vals = self._pref_matrix.get(did, [])
            if not vals:
                continue
            syn = float(np.mean(vals))
            rel_dev = abs(syn - ref) / ref
            deviations[did] = {
                "synthetic_mean": round(syn, 3),
                "reference":      ref,
                "relative_error": round(rel_dev, 3),
            }
        if not deviations:
            return 0.0, {}
        score = float(np.clip(
            1.0 - np.mean([d["relative_error"] for d in deviations.values()]), 0.0, 1.0
        ))
        return round(score, 4), deviations

    # ── MDP: Monotone Demographic Predictions ─────────────────────────────────

    def monotone_demographic_predictions(self) -> tuple[float, list[dict]]:
        """
        Test that preferences follow expected signed relationships with age and income.

        For each (layer, feature, expected_sign) in MONOTONE_CHECKS:
          ρ = Spearman rank correlation(preference_vector, demographic_vector)
          pass = sign(ρ) matches expected_sign

        Score = fraction of checks that pass.

        References: Golledge & Stimson 1997; MTUS W6; ATUS 2022.
        """
        self._build()
        results = []
        correct = 0
        for did, feat, expected in MONOTONE_CHECKS:
            vals = self._pref_matrix.get(did, [])
            if len(vals) < 10:
                continue
            demo = self._age_vector if feat == "age" else self._inc_vector
            demo_aligned = demo[:len(vals)]
            if np.std(vals) < 1e-6 or np.std(demo_aligned) < 1e-6:
                results.append({
                    "layer": did, "feature": feat,
                    "expected": expected, "rho": None, "pass": False,
                })
                continue
            rho, _ = stats.spearmanr(vals, demo_aligned)
            passed = (rho > 0 and expected == "positive") or \
                     (rho < 0 and expected == "negative")
            if passed:
                correct += 1
            results.append({
                "layer":    did,
                "feature":  feat,
                "expected": expected,
                "rho":      round(float(rho), 3),
                "pass":     passed,
            })
        score = correct / len(results) if results else 0.0
        return round(score, 4), results

    # ── SCC: Social Cluster Coherence ─────────────────────────────────────────

    def social_cluster_coherence(self) -> tuple[float, list[dict]]:
        """
        Test that social/leisure destinations (D21, D22, D23, D24) have positive
        pairwise Pearson correlations (common driver: extraversion + hedonism).

        Score = fraction of pairs with r > 0.

        Theoretical basis: Ben-Akiva & Lerman (1985), shared latent utility;
        McCrae & Costa (2003), extraversion as common predictor.
        """
        self._build()
        ids    = SOCIAL_CLUSTER
        pairs  = [(ids[i], ids[j]) for i in range(len(ids)) for j in range(i + 1, len(ids))]
        results = []
        positive = 0
        for a, b in pairs:
            va = self._pref_matrix.get(a, [])
            vb = self._pref_matrix.get(b, [])
            n  = min(len(va), len(vb))
            if n < 10 or np.std(va[:n]) < 1e-6 or np.std(vb[:n]) < 1e-6:
                continue
            r, _ = stats.pearsonr(va[:n], vb[:n])
            passed = r > 0
            if passed:
                positive += 1
            results.append({"pair": f"{a}×{b}", "r": round(float(r), 3), "pass": passed})
        score = positive / len(results) if results else 0.0
        return round(score, 4), results

    # ── SEF: Shannon Entropy Floor ─────────────────────────────────────────────

    def shannon_entropy_floor(self, threshold: float = 0.65) -> tuple[float, dict]:
        """
        Fraction of agents whose preference vector has normalised Shannon entropy
        ≥ threshold (default 0.65).

        H(agent) = -Σ_d p_d · log(p_d)   [nats]
        H_norm   = H(agent) / log(K)       where K = number of modelled layers

        threshold = 0.65 means the agent's preferences are spread across at least
        K^0.65 ≈ 10.3 effective destination types (for K=23), preventing extreme
        concentration on a single layer.

        Theoretical basis: Shannon (1948); Harte et al. (2008) maximum entropy
        principle applied to activity-type distributions.
        """
        self._build()
        K = len([d for d in ALL_LAYER_IDS if self._pref_matrix.get(d)])
        if K < 2:
            return 0.0, {}
        h_max = math.log(K)
        h_vals = []
        for i in range(len(self.profiles)):
            pvec = []
            for did in ALL_LAYER_IDS:
                vals = self._pref_matrix.get(did, [])
                if i < len(vals):
                    pvec.append(vals[i])
            if not pvec:
                continue
            pvec_a = np.array(pvec, dtype=float)
            pvec_a = pvec_a / pvec_a.sum()
            h_raw  = -float(np.sum(pvec_a * np.log(np.clip(pvec_a, 1e-12, 1.0))))
            h_vals.append(h_raw / h_max)
        if not h_vals:
            return 0.0, {}
        fraction_above = float(np.mean(np.array(h_vals) >= threshold))
        return round(fraction_above, 4), {
            "threshold":         threshold,
            "mean_h_norm":       round(float(np.mean(h_vals)), 3),
            "sd_h_norm":         round(float(np.std(h_vals)),  3),
            "min_h_norm":        round(float(np.min(h_vals)),  3),
            "fraction_above":    round(fraction_above, 4),
            "n_layers":          K,
        }

    # ── Composite report ──────────────────────────────────────────────────────

    def report(self) -> dict:
        """
        Run all four validity metrics and return a structured report dict.

        Keys
        ────
        ara         — Activity Rate Alignment score [0, 1]
        mdp         — Monotone Demographic Predictions score [0, 1]
        scc         — Social Cluster Coherence score [0, 1]
        sef         — Shannon Entropy Floor score [0, 1]
        composite   — unweighted mean of the four scores
        detail_*    — raw sub-results for each metric
        n_profiles  — number of profiles evaluated
        """
        ara, ara_d = self.activity_rate_alignment()
        mdp, mdp_d = self.monotone_demographic_predictions()
        scc, scc_d = self.social_cluster_coherence()
        sef, sef_d = self.shannon_entropy_floor()
        composite  = round(float(np.mean([ara, mdp, scc, sef])), 4)

        return {
            "ara":        ara,
            "mdp":        mdp,
            "scc":        scc,
            "sef":        sef,
            "composite":  composite,
            "detail_ara": ara_d,
            "detail_mdp": mdp_d,
            "detail_scc": scc_d,
            "detail_sef": sef_d,
            "n_profiles": len(self.profiles),
        }


# ── Population-level recalibration to reference rates (V2.2) ───────────────────

def calibrate_to_reference(population: list, max_scale: float = 6.0) -> int:
    """
    Rescale each adult agent's place_preferences so the POPULATION MEAN per layer
    matches its Eurostat reference base rate, in logit space.

    Why logit space: a per-layer additive logit shift is the natural mean-matching
    transform for logistic-bounded probabilities — it preserves each agent's
    rank-order within a layer (so MDP / SCC / SEF are invariant) while moving the
    population mean onto the reference rate (so ARA → ~1). This replaces the
    deprecated 15-layer μₖ/Jensen calibration with a direct 26-layer correction.

    Operates on adults only (children's prefs are not Eurostat-comparable) and
    mutates place_preferences in place. Returns the number of agents calibrated.
    """
    import numpy as _np

    def _logit(p):  return _np.log(p / (1.0 - p))
    def _sig(x):    return 1.0 / (1.0 + _np.exp(-x))

    adults = [a for a in population
              if not a.get("is_minor", False) and a.get("place_preferences")]
    if not adults:
        return 0

    for did, ref in _ARA_TARGETS.items():
        vals = _np.array([a["place_preferences"].get(did) for a in adults
                          if a["place_preferences"].get(did) is not None], dtype=float)
        if len(vals) == 0:
            continue
        vals = _np.clip(vals, 0.01, 0.99)
        cur_mean = float(vals.mean())
        if cur_mean <= 0 or cur_mean >= 1:
            continue
        # additive logit shift that moves the mean of the logistic onto ref
        shift = _logit(min(max(ref, 0.01), 0.99)) - _logit(min(max(cur_mean, 0.01), 0.99))
        shift = float(_np.clip(shift, -_np.log(max_scale) * 2, _np.log(max_scale) * 2))
        for a in adults:
            p = a["place_preferences"].get(did)
            if p is None:
                continue
            p = min(max(float(p), 0.01), 0.99)
            a["place_preferences"][did] = round(float(_sig(_logit(p) + shift)), 3)

    return len(adults)
